/**
 * Pre-generated Audience Insights Reports
 * 
 * This file contains pre-generated reports for all audience segments.
 * Generated at build time to ensure instant loading and perfect quality.
 * 
 * Last Generated: 2025-12-20T05:35:14.532Z
 * Total Reports: 1
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate using: npm run pregenerate:insights
 */

import type { PreGeneratedAudienceReport } from './audienceInsightsReports';

export const audienceInsightsReports: Record<string, PreGeneratedAudienceReport> = {
  "Coffee": {
    "segment": "Coffee",
    "category": "General",
    "executiveSummary": "Let's better understand people in the market for Coffee. The convergence of significantly above-national-average income and education levels points to a professional demographic that prioritizes efficiency and quality in their daily lives. Their strong cross-shopping with Household Supplies and Exercise & Fitness reveals a busy, family-oriented lifestyle focused on maintaining a home and personal well-being, where coffee serves as a vital functional necessity for energy and productivity. Furthermore, the high STEM education rate suggests a discerning approach to product evaluation, indicating a preference for coffee products with specific attributes, quality sourcing, or functional benefits that align with their demanding routines and health-conscious values.",
    "personaName": "The Ambitious Coffee Balancer",
    "personaEmoji": "☕",
    "personaDescription": "Meet Alex, a visionary entrepreneur navigating the bustling pace of cities like Seattle or Los Angeles. Their days are a dynamic blend of building a business and cherishing family moments, often starting before dawn with a clear vision for both. Coffee isn't just a drink; it's the essential fuel for their creative drive and a cherished ritual that anchors their busy schedule. They seek out quality and consistency, frustrated by anything that wastes their precious time or falls short of their high standards, whether it's for their morning brew or the household essentials they manage.",
    "keyMetrics": {
      "medianHHI": 89746.18184539847,
      "medianHHIvsNational": 27.44416621044941,
      "medianHHIvsCommerce": -15.469358721485849,
      "topAgeBracket": "30-39",
      "educationLevel": 52.16935512843544,
      "educationVsNational": 49.055300366958406,
      "educationVsCommerce": -12.760275704957447
    },
    "geographicHotspots": [
      {
        "zipCode": "94102",
        "city": "San Francisco",
        "state": "California",
        "density": 988,
        "population": 34983,
        "overIndex": 33708.11026406716
      },
      {
        "zipCode": "98104",
        "city": "Seattle",
        "state": "Washington",
        "density": 979,
        "population": 15870,
        "overIndex": 73627.53764258284
      },
      {
        "zipCode": "90003",
        "city": "Los Angeles",
        "state": "California",
        "density": 899,
        "population": 71708,
        "overIndex": 14963.27278388957
      },
      {
        "zipCode": "33126",
        "city": "Miami",
        "state": "Florida",
        "density": 884,
        "population": 47038,
        "overIndex": 22430.447010651686
      },
      {
        "zipCode": "98102",
        "city": "Seattle",
        "state": "Washington",
        "density": 874,
        "population": 26583,
        "overIndex": 39241.17045807299
      },
      {
        "zipCode": "60601",
        "city": "Chicago",
        "state": "Illinois",
        "density": 873,
        "population": 16292,
        "overIndex": 63954.97796875437
      },
      {
        "zipCode": "90001",
        "city": "Los Angeles",
        "state": "California",
        "density": 848,
        "population": 56403,
        "overIndex": 17944.36768552643
      },
      {
        "zipCode": "98105",
        "city": "Seattle",
        "state": "Washington",
        "density": 840,
        "population": 49229,
        "overIndex": 20365.39244767685
      },
      {
        "zipCode": "90002",
        "city": "Los Angeles",
        "state": "California",
        "density": 815,
        "population": 52735,
        "overIndex": 18445.616275841185
      },
      {
        "zipCode": "75205",
        "city": "Dallas",
        "state": "Texas",
        "density": 772,
        "population": 25537,
        "overIndex": 36081.27994071906
      },
      {
        "zipCode": "85003",
        "city": "Phoenix",
        "state": "Arizona",
        "density": 718,
        "population": 10155,
        "overIndex": 84387.67621523517
      },
      {
        "zipCode": "98103",
        "city": "Seattle",
        "state": "Washington",
        "density": 681,
        "population": 51988,
        "overIndex": 15634.302585700905
      },
      {
        "zipCode": "19104",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "density": 675,
        "population": 54454,
        "overIndex": 14794.779511245653
      },
      {
        "zipCode": "10001",
        "city": "New York",
        "state": "New York",
        "density": 650,
        "population": 29079,
        "overIndex": 26678.92957134606
      },
      {
        "zipCode": "85004",
        "city": "Phoenix",
        "state": "Arizona",
        "density": 638,
        "population": 11178,
        "overIndex": 68122.57956388232
      },
      {
        "zipCode": "10002",
        "city": "New York",
        "state": "New York",
        "density": 592,
        "population": 75517,
        "overIndex": 9356.458363609658
      },
      {
        "zipCode": "75201",
        "city": "Dallas",
        "state": "Texas",
        "density": 536,
        "population": 18078,
        "overIndex": 35387.421502614496
      },
      {
        "zipCode": "98101",
        "city": "Seattle",
        "state": "Washington",
        "density": 504,
        "population": 16396,
        "overIndex": 36688.261947060884
      },
      {
        "zipCode": "94103",
        "city": "San Francisco",
        "state": "California",
        "density": 486,
        "population": 33524,
        "overIndex": 17302.74265970251
      },
      {
        "zipCode": "90004",
        "city": "Los Angeles",
        "state": "California",
        "density": 376,
        "population": 58844,
        "overIndex": 7626.410351488542
      },
      {
        "zipCode": "75203",
        "city": "Dallas",
        "state": "Texas",
        "density": 372,
        "population": 15710,
        "overIndex": 28261.89419751496
      },
      {
        "zipCode": "60605",
        "city": "Chicago",
        "state": "Illinois",
        "density": 328,
        "population": 34256,
        "overIndex": 11428.03877167824
      },
      {
        "zipCode": "94105",
        "city": "San Francisco",
        "state": "California",
        "density": 293,
        "population": 14890,
        "overIndex": 23485.912254018225
      },
      {
        "zipCode": "94107",
        "city": "San Francisco",
        "state": "California",
        "density": 223,
        "population": 30190,
        "overIndex": 8816.09500039001
      },
      {
        "zipCode": "10003",
        "city": "New York",
        "state": "New York",
        "density": 201,
        "population": 53825,
        "overIndex": 4457.039985538306
      },
      {
        "zipCode": "75204",
        "city": "Dallas",
        "state": "Texas",
        "density": 198,
        "population": 33552,
        "overIndex": 7043.382736098458
      },
      {
        "zipCode": "19103",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "density": 161,
        "population": 25602,
        "overIndex": 7505.6186400000415
      },
      {
        "zipCode": "33125",
        "city": "Miami",
        "state": "Florida",
        "density": 160,
        "population": 55449,
        "overIndex": 3443.981229621329
      },
      {
        "zipCode": "90005",
        "city": "Los Angeles",
        "state": "California",
        "density": 137,
        "population": 38747,
        "overIndex": 4220.04416189873
      }
    ],
    "demographics": {
      "incomeDistribution": [
        {
          "bracket": "Under $50k",
          "percentage": 10.771810071253219,
          "nationalAvg": 35
        },
        {
          "bracket": "$50k-$75k",
          "percentage": 43.60217951020897,
          "nationalAvg": 25
        },
        {
          "bracket": "$75k-$100k",
          "percentage": 7.1792108256990605,
          "nationalAvg": 18
        },
        {
          "bracket": "$100k-$150k",
          "percentage": 29.531165798455184,
          "nationalAvg": 15
        },
        {
          "bracket": "$150k+",
          "percentage": 8.915633794383568,
          "nationalAvg": 7
        }
      ],
      "educationLevels": [
        {
          "level": "Graduate Degree",
          "percentage": 71.81605891862762
        },
        {
          "level": "High School or Less",
          "percentage": 17.567810310759835
        },
        {
          "level": "Some College",
          "percentage": 6.251122687264235
        },
        {
          "level": "Bachelor's Degree",
          "percentage": 4.365008083348303
        }
      ],
      "ageDistribution": [
        {
          "bracket": "0-9",
          "percentage": 9.745720136518772
        },
        {
          "bracket": "10-19",
          "percentage": 9.680328920423927
        },
        {
          "bracket": "20-29",
          "percentage": 15.894013801568766
        },
        {
          "bracket": "30-39",
          "percentage": 22.303229860487402
        },
        {
          "bracket": "40-49",
          "percentage": 18.878026962457337
        },
        {
          "bracket": "50-59",
          "percentage": 10.877639662295673
        },
        {
          "bracket": "60-69",
          "percentage": 5.6690865816418174
        },
        {
          "bracket": "70+",
          "percentage": 6.928883599784445
        }
      ],
      "ethnicity": {
        "white": 46.29625770911921,
        "hispanic": 31.364014130890364,
        "asian": 15.67034309322795,
        "black": 10.016969043769834
      },
      "lifestyle": {
        "selfEmployed": 16.54224297946231,
        "married": 31.4931501107718,
        "dualIncome": 56.15413448296509,
        "avgCommuteTime": 27.140841865756546,
        "charitableGivers": 22.228082150769417,
        "stemDegree": 50.467558828812635
      },
      "medianHomeValue": 728041.5245793666,
      "homeOwnership": 27.395772708221067,
      "avgHouseholdSize": 2.9934351236452894,
      "urbanRuralDistribution": [
        {
          "type": "suburban",
          "percentage": 68.58271959762888
        },
        {
          "type": "urban",
          "percentage": 31.417280402371116
        }
      ]
    },
    "behavioralOverlap": [
      {
        "segment": "Household Supplies",
        "overlapPercentage": 52,
        "insight": "Coffee buyers are practical, home-focused individuals who regularly purchase household essentials and cleaning supplies, indicating routine shopping patterns and receptiveness to bundled household product offerings.",
        "overIndex": 10,
        "topMarkets": [
          {
            "city": "San Francisco",
            "state": "California",
            "overIndex": 1.6779934949546393
          },
          {
            "city": "Phoenix",
            "state": "Arizona",
            "overIndex": 1.464285718419025
          },
          {
            "city": "Philadelphia",
            "state": "Pennsylvania",
            "overIndex": 1.3906157661094256
          }
        ]
      },
      {
        "segment": "Exercise & Fitness",
        "overlapPercentage": 50,
        "insight": "Coffee buyers maintain active, health-conscious lifestyles, investing in fitness and exercise products alongside their purchases, creating cross-selling opportunities for wellness, nutrition, and athletic products.",
        "overIndex": 10,
        "topMarkets": [
          {
            "city": "Seattle",
            "state": "Washington",
            "overIndex": 1.623471194096424
          },
          {
            "city": "Los Angeles",
            "state": "California",
            "overIndex": 1.572689026990511
          },
          {
            "city": "New York",
            "state": "New York",
            "overIndex": 1.331269578680229
          }
        ]
      },
      {
        "segment": "Alcoholic Beverages",
        "overlapPercentage": 46,
        "insight": "Coffee buyers enjoy social entertaining and relaxation rituals, purchasing alcoholic beverages to complement their lifestyle, indicating sophistication and willingness to invest in quality experiences beyond basic necessities.",
        "overIndex": 10,
        "topMarkets": [
          {
            "city": "Chicago",
            "state": "Illinois",
            "overIndex": 1.4647419911347388
          },
          {
            "city": "Miami",
            "state": "Florida",
            "overIndex": 1.3544761419836884
          },
          {
            "city": "Dallas",
            "state": "Texas",
            "overIndex": 1.1103583333622717
          }
        ]
      },
      {
        "segment": "Laptops",
        "overlapPercentage": 44,
        "insight": "Coffee buyers include remote workers and tech professionals who invest in laptops and computing equipment, creating opportunities for home office products, productivity software, and tech accessories.",
        "overIndex": 10,
        "topMarkets": [
          {
            "city": "Miami Beach",
            "state": "Florida",
            "overIndex": 1.2158719794797235
          }
        ]
      },
      {
        "segment": "Shaving & Grooming",
        "overlapPercentage": 44,
        "insight": "Coffee buyers value personal care and grooming, maintaining daily self-care routines that create opportunities for subscription services and complementary wellness products.",
        "overIndex": 10,
        "topMarkets": []
      }
    ],
    "strategicInsights": {
      "targetPersona": "Focused Fiona is a **driven**, **intentional**, college-educated professional in her late 30s who manages a dynamic, family-focused household in Seattle or Los Angeles. As an entrepreneurial professional with Upper-Middle Affluence, she values efficiency and quality in all aspects of her well-curated life. Driven by both the practical demands of household management (52% overlap with Household Supplies) and a commitment to personal well-being (50% overlap with Exercise & Fitness), Fiona seeks premium coffee that provides sustained energy, supports her daily rituals, and aligns with her values of quality and mindful living.",
      "messagingRecommendations": [
        {
          "valueProposition": "**Smart Value for Busy Families**",
          "dataBacking": "The 'Coffee' audience has -15.5% lower Median HHI vs. Commerce Baseline, with an average household size of 3.0 people and 72% of top ZIPs indicating likely children. This highlights a need for cost-effective solutions for larger households.",
          "emotionalBenefit": "Offers **peace of mind** by providing quality coffee that fits the family budget, allowing more resources for other family needs and experiences.",
          "campaignReady": true
        },
        {
          "valueProposition": "**Fueling the Modern Professional & Entrepreneur**",
          "dataBacking": "52.2% of this audience has a Bachelor's degree+, 16.5% are self-employed, and 50.5% have a STEM degree, indicating a highly educated, professional, and often entrepreneurial segment.",
          "emotionalBenefit": "Positions coffee as an **essential tool** for productivity, focus, and innovation, supporting their ambitious careers and flexible work styles.",
          "campaignReady": true
        },
        {
          "valueProposition": "**Quality & Convenience for the Tech-Savvy Home**",
          "dataBacking": "50.5% of the audience has a STEM degree, 69% live in suburban areas, and 'Laptops' are a top behavioral overlap (44%). This suggests a preference for efficient, tech-integrated home solutions.",
          "emotionalBenefit": "Delivers **effortless enjoyment** and a sophisticated experience, appealing to their appreciation for smart design and seamless integration into their modern, connected homes.",
          "campaignReady": true
        }
      ],
      "channelRecommendations": [
        {
          "platform": "Instagram (Reels & Stories)",
          "targeting": "25-40 year-olds in Seattle, Los Angeles, Phoenix, and Dallas, interested in 'Household Supplies,' 'Exercise & Fitness,' and 'Laptops.'",
          "contentType": "Short-form video showcasing coffee rituals (morning routine, work-from-home breaks, family moments), DIY coffee recipes, and product features in an engaging, visually appealing way.",
          "timing": "Early mornings (6-9 AM), lunch breaks (12-1 PM), and evenings (7-9 PM) when parents are winding down or planning for the next day.",
          "rationale": "The audience's median age is 34.1, with the dominant bracket being 30-39, aligning well with Instagram's primary user base. High STEM degree (50.5%) suggests tech-savviness and receptiveness to visual, dynamic content. Overlaps with 'Exercise & Fitness' and 'Household Supplies' indicate lifestyle alignment.",
          "estimatedPerformance": {
            "expectedCTR": "2.1-2.8%",
            "targetCPM": "$12-18",
            "conversionRate": "1.2-2.1%"
          }
        },
        {
          "platform": "LinkedIn (Sponsored Content & InMail)",
          "targeting": "Professionals aged 30-49, self-employed or in STEM fields, located in top volume markets like San Francisco, New York, and Seattle.",
          "contentType": "Articles or short videos focusing on coffee's role in productivity, focus, and work-life balance for entrepreneurs and knowledge workers. Could include B2B offers for office coffee solutions.",
          "timing": "Weekday business hours (9 AM - 5 PM), particularly mid-morning and mid-afternoon breaks.",
          "rationale": "16.5% self-employed and 50.5% with STEM degrees indicate a strong professional and entrepreneurial bent. LinkedIn provides direct access to this segment for B2B or professional-oriented messaging.",
          "estimatedPerformance": {
            "expectedCTR": "0.8-1.5%",
            "targetCPM": "$25-40",
            "conversionRate": "0.5-1.0%"
          }
        },
        {
          "platform": "Google Search & Shopping Ads",
          "targeting": "Broad keyword targeting for 'value coffee,' 'family-size coffee,' 'best coffee for home office,' 'sustainable coffee brands,' and geo-targeting to top volume and passion markets.",
          "contentType": "Product listing ads (PLAs) for specific coffee products, text ads highlighting value propositions (e.g., 'Affordable Quality Coffee,' 'Bulk Coffee for Families'), and landing pages optimized for conversion.",
          "timing": "Consistent, always-on presence, with potential budget increases during peak shopping times (e.g., weekends, early mornings).",
          "rationale": "As 'Value-Conscious Shoppers' (-15.5% income vs. Commerce Baseline), this audience is likely to actively search for specific products and compare prices. High education (52.2% Bachelor's+) suggests they research purchases.",
          "estimatedPerformance": {
            "expectedCTR": "3.5-5.0%",
            "targetCPM": "$8-15 (CPC model)",
            "conversionRate": "2.5-4.0%"
          }
        }
      ],
      "implementationRoadmap": {
        "phase1": {
          "duration": "2-3 weeks",
          "budget": "$5,000-$8,000",
          "actions": [
            "Develop 3-4 creative concepts for Instagram (Reels/Stories) and Google Search, focusing on 'Value for Families' and 'Productivity Fuel'.",
            "Launch geo-targeted campaigns in Seattle (98104, 98102) and Phoenix (85003, 85004) – top passion markets for testing.",
            "Implement basic conversion tracking and A/B test creative variants and ad copy."
          ],
          "successMetrics": {
            "CTR": ">2.0%",
            "CPA": "<$65",
            "ROAS": ">3.5x"
          }
        },
        "phase2": {
          "duration": "4-6 weeks",
          "budget": "$15,000-$25,000",
          "actions": [
            "Scale winning creative and messaging to additional top volume markets (Los Angeles, San Francisco, Dallas, New York).",
            "Expand to LinkedIn with B2B-focused content for self-employed and STEM professionals.",
            "Implement advanced attribution tracking to understand cross-channel impact and optimize budget allocation.",
            "Explore partnership opportunities with 'Exercise & Fitness' or 'Household Supplies' brands based on behavioral overlaps."
          ],
          "successMetrics": {
            "Volume": "800+ conversions",
            "Efficiency": "20% improvement in CPA"
          }
        }
      },
      "competitiveIntelligence": {
        "marketPosition": "This 'Coffee' segment is distinct from the typical online shopper, being more **value-conscious** (-15.5% HHI vs. Commerce Baseline) but still **highly educated** (52.2% Bachelor's+) and **tech-savvy** (50.5% STEM degree). They are often **family-focused** (avg. household size 3.0, 72% ZIPs with children) and have a significant proportion of **self-employed professionals** (16.5%). This contrasts with a general perception of coffee consumers as purely premium-seeking or solely convenience-driven.",
        "whiteSpaceOpportunities": [
          "**B2B Cross-Sell for Home Offices**: Target self-employed individuals (16.5%) with bulk or subscription coffee tailored for home office productivity, potentially bundling with 'Laptops' or other office supplies.",
          "**Ethical Sourcing & Sustainability Messaging**: Leverage the 'Charitable Givers' (22.2%) insight by emphasizing fair trade, organic, or sustainable coffee options, appealing to their values without necessarily demanding a premium price.",
          "**Tech-Integrated Coffee Solutions**: For the 50.5% with STEM degrees, explore smart coffee makers, subscription services with personalized recommendations, or app-controlled brewing, positioning coffee as a modern, efficient lifestyle component.",
          "**Family-Sized & Value Bundles**: Directly address the larger household size (3.0 people) and value-consciousness with larger packs, subscription discounts, or multi-product bundles that cater to family consumption."
        ],
        "differentiationAdvantages": [
          "**Educated Value Seekers**: Unlike purely budget-driven segments, this audience seeks value without sacrificing quality, informed by their education and tech-savviness. They appreciate clear, data-backed reasons for a product's value.",
          "**Productivity-Driven Consumption**: The high percentage of self-employed and STEM professionals means coffee is often viewed as a functional tool for focus and energy, not just a leisure beverage. Messaging can lean into performance benefits.",
          "**Suburban Family Hub**: Their suburban, family-focused lifestyle means coffee consumption is often centered around the home, offering opportunities for at-home brewing solutions and family-friendly messaging.",
          "**Early Adopter Potential**: High STEM degree holders are likely early adopters of new technologies and innovative products, making them receptive to new coffee formats, brewing methods, or smart appliances."
        ]
      },
      "seasonalOptimization": {
        "peakPeriods": [
          "**Back-to-School/Fall (August-September)**: Increased need for routine and energy as families adjust to school schedules and parents return to full work focus. Overlaps with 'Household Supplies' for restocking.",
          "**Holiday Season (November-December)**: Gifting opportunities for coffee-related products, special blends, and home brewing equipment. Also a time for increased entertaining and family gatherings.",
          "**New Year, New Routines (January)**: Aligns with 'Exercise & Fitness' overlap, as people establish new health and productivity goals, making coffee a part of their renewed routines.",
          "**Spring Refresh (March-April)**: As weather improves, focus on iced coffee, lighter roasts, and coffee for outdoor activities or spring cleaning energy."
        ],
        "opportunityWindows": [
          "**New Product Launches**: Introduce innovative coffee products or brewing accessories during Q1 (post-holiday) or Q3 (back-to-school) to capture attention from tech-savvy early adopters.",
          "**Subscription Service Promotions**: Promote subscription models during periods of routine establishment (Jan, Aug/Sep) to emphasize convenience and consistent value.",
          "**Work-From-Home Campaigns**: Ongoing opportunity, but particularly strong during colder months or periods of increased remote work, targeting the self-employed segment.",
          "**Local/Regional Events**: Leverage geographic insights by sponsoring or participating in local community events in top passion markets (Phoenix, Seattle) to build brand loyalty."
        ],
        "budgetAllocation": [
          "**Q1 (Jan-Mar)**: 25% - Capitalize on New Year resolutions and post-holiday sales, focus on productivity and wellness messaging.",
          "**Q2 (Apr-Jun)**: 20% - Steady spend, focus on lighter roasts, iced coffee, and outdoor consumption.",
          "**Q3 (Jul-Sep)**: 30% - Significant increase for back-to-school, routine establishment, and early fall promotions.",
          "**Q4 (Oct-Dec)**: 25% - Strong push for holiday gifting, entertaining, and seasonal blends."
        ]
      }
    }
  },

};
